create table departamento
(
    id          bigint generated by default as identity
        primary key,
    gasto       numeric(12, 2) not null,
    nombre      varchar(255)   not null
        constraint uk_departamento_nombre
            unique,
    presupuesto numeric(12, 2) not null
);

alter table departamento
    owner to postgres;

create table empleado
(
    id              bigint generated by default as identity
        primary key,
    apellido1       varchar(100) not null,
    apellido2       varchar(100),
    departamento_id bigint
        constraint fkhdjjhohpyjsfta5g6p8b8e00i
            references departamento
            on delete cascade,
    nif             varchar(9)   not null
        constraint uk_empleado_nif
            unique,
    nombre          varchar(100) not null
);

alter table empleado
    owner to postgres;

create index idx_empleado_departamento_id
    on empleado (departamento_id);
